// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: shared/proto/siphon.proto

package siphon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngressService_StreamTestResults_FullMethodName = "/siphon.IngressService/StreamTestResults"
)

// IngressServiceClient is the client API for IngressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definitions
type IngressServiceClient interface {
	StreamTestResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TestResultStreamRequest, TestResultStreamResponse], error)
}

type ingressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngressServiceClient(cc grpc.ClientConnInterface) IngressServiceClient {
	return &ingressServiceClient{cc}
}

func (c *ingressServiceClient) StreamTestResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TestResultStreamRequest, TestResultStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngressService_ServiceDesc.Streams[0], IngressService_StreamTestResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TestResultStreamRequest, TestResultStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngressService_StreamTestResultsClient = grpc.ClientStreamingClient[TestResultStreamRequest, TestResultStreamResponse]

// IngressServiceServer is the server API for IngressService service.
// All implementations must embed UnimplementedIngressServiceServer
// for forward compatibility.
//
// Service definitions
type IngressServiceServer interface {
	StreamTestResults(grpc.ClientStreamingServer[TestResultStreamRequest, TestResultStreamResponse]) error
	mustEmbedUnimplementedIngressServiceServer()
}

// UnimplementedIngressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngressServiceServer struct{}

func (UnimplementedIngressServiceServer) StreamTestResults(grpc.ClientStreamingServer[TestResultStreamRequest, TestResultStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTestResults not implemented")
}
func (UnimplementedIngressServiceServer) mustEmbedUnimplementedIngressServiceServer() {}
func (UnimplementedIngressServiceServer) testEmbeddedByValue()                        {}

// UnsafeIngressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngressServiceServer will
// result in compilation errors.
type UnsafeIngressServiceServer interface {
	mustEmbedUnimplementedIngressServiceServer()
}

func RegisterIngressServiceServer(s grpc.ServiceRegistrar, srv IngressServiceServer) {
	// If the following call panics, it indicates UnimplementedIngressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngressService_ServiceDesc, srv)
}

func _IngressService_StreamTestResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngressServiceServer).StreamTestResults(&grpc.GenericServerStream[TestResultStreamRequest, TestResultStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngressService_StreamTestResultsServer = grpc.ClientStreamingServer[TestResultStreamRequest, TestResultStreamResponse]

// IngressService_ServiceDesc is the grpc.ServiceDesc for IngressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "siphon.IngressService",
	HandlerType: (*IngressServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTestResults",
			Handler:       _IngressService_StreamTestResults_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "shared/proto/siphon.proto",
}
