// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: shared/proto/siphon.proto

package siphon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestCase_Status int32

const (
	TestCase_UNKNOWN TestCase_Status = 0
	TestCase_PASS    TestCase_Status = 1
	TestCase_FAIL    TestCase_Status = 2
	TestCase_SKIPPED TestCase_Status = 3
)

// Enum value maps for TestCase_Status.
var (
	TestCase_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PASS",
		2: "FAIL",
		3: "SKIPPED",
	}
	TestCase_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"PASS":    1,
		"FAIL":    2,
		"SKIPPED": 3,
	}
)

func (x TestCase_Status) Enum() *TestCase_Status {
	p := new(TestCase_Status)
	*p = x
	return p
}

func (x TestCase_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestCase_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_siphon_proto_enumTypes[0].Descriptor()
}

func (TestCase_Status) Type() protoreflect.EnumType {
	return &file_shared_proto_siphon_proto_enumTypes[0]
}

func (x TestCase_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestCase_Status.Descriptor instead.
func (TestCase_Status) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_siphon_proto_rawDescGZIP(), []int{3, 0}
}

type TestStep_Status int32

const (
	TestStep_UNKNOWN TestStep_Status = 0
	TestStep_PASS    TestStep_Status = 1
	TestStep_FAIL    TestStep_Status = 2
	TestStep_SKIPPED TestStep_Status = 3
)

// Enum value maps for TestStep_Status.
var (
	TestStep_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PASS",
		2: "FAIL",
		3: "SKIPPED",
	}
	TestStep_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"PASS":    1,
		"FAIL":    2,
		"SKIPPED": 3,
	}
)

func (x TestStep_Status) Enum() *TestStep_Status {
	p := new(TestStep_Status)
	*p = x
	return p
}

func (x TestStep_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestStep_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_siphon_proto_enumTypes[1].Descriptor()
}

func (TestStep_Status) Type() protoreflect.EnumType {
	return &file_shared_proto_siphon_proto_enumTypes[1]
}

func (x TestStep_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestStep_Status.Descriptor instead.
func (TestStep_Status) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_siphon_proto_rawDescGZIP(), []int{4, 0}
}

type TestResultStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestSuite     *TestSuite             `protobuf:"bytes,1,opt,name=test_suite,json=testSuite,proto3" json:"test_suite,omitempty"`
	TestCase      *TestCase              `protobuf:"bytes,2,opt,name=test_case,json=testCase,proto3" json:"test_case,omitempty"`
	TestSteps     []*TestStep            `protobuf:"bytes,3,rep,name=test_steps,json=testSteps,proto3" json:"test_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResultStreamRequest) Reset() {
	*x = TestResultStreamRequest{}
	mi := &file_shared_proto_siphon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResultStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResultStreamRequest) ProtoMessage() {}

func (x *TestResultStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_siphon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResultStreamRequest.ProtoReflect.Descriptor instead.
func (*TestResultStreamRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_siphon_proto_rawDescGZIP(), []int{0}
}

func (x *TestResultStreamRequest) GetTestSuite() *TestSuite {
	if x != nil {
		return x.TestSuite
	}
	return nil
}

func (x *TestResultStreamRequest) GetTestCase() *TestCase {
	if x != nil {
		return x.TestCase
	}
	return nil
}

func (x *TestResultStreamRequest) GetTestSteps() []*TestStep {
	if x != nil {
		return x.TestSteps
	}
	return nil
}

type TestResultStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResultStreamResponse) Reset() {
	*x = TestResultStreamResponse{}
	mi := &file_shared_proto_siphon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResultStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResultStreamResponse) ProtoMessage() {}

func (x *TestResultStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_siphon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResultStreamResponse.ProtoReflect.Descriptor instead.
func (*TestResultStreamResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_siphon_proto_rawDescGZIP(), []int{1}
}

func (x *TestResultStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestResultStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Data Structures
type TestSuite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Project       string                 `protobuf:"bytes,6,opt,name=project,proto3" json:"project,omitempty"`
	Release       string                 `protobuf:"bytes,7,opt,name=release,proto3" json:"release,omitempty"`
	Sprint        string                 `protobuf:"bytes,8,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSuite) Reset() {
	*x = TestSuite{}
	mi := &file_shared_proto_siphon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSuite) ProtoMessage() {}

func (x *TestSuite) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_siphon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSuite.ProtoReflect.Descriptor instead.
func (*TestSuite) Descriptor() ([]byte, []int) {
	return file_shared_proto_siphon_proto_rawDescGZIP(), []int{2}
}

func (x *TestSuite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestSuite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestSuite) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *TestSuite) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TestSuite) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TestSuite) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TestSuite) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *TestSuite) GetSprint() string {
	if x != nil {
		return x.Sprint
	}
	return ""
}

type TestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SuiteId       string                 `protobuf:"bytes,2,opt,name=suite_id,json=suiteId,proto3" json:"suite_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        TestCase_Status        `protobuf:"varint,4,opt,name=status,proto3,enum=siphon.TestCase_Status" json:"status,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ScreenshotUrl string                 `protobuf:"bytes,7,opt,name=screenshot_url,json=screenshotUrl,proto3" json:"screenshot_url,omitempty"` // MinIO uploaded public screenshot path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCase) Reset() {
	*x = TestCase{}
	mi := &file_shared_proto_siphon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCase) ProtoMessage() {}

func (x *TestCase) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_siphon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCase.ProtoReflect.Descriptor instead.
func (*TestCase) Descriptor() ([]byte, []int) {
	return file_shared_proto_siphon_proto_rawDescGZIP(), []int{3}
}

func (x *TestCase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCase) GetSuiteId() string {
	if x != nil {
		return x.SuiteId
	}
	return ""
}

func (x *TestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestCase) GetStatus() TestCase_Status {
	if x != nil {
		return x.Status
	}
	return TestCase_UNKNOWN
}

func (x *TestCase) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TestCase) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TestCase) GetScreenshotUrl() string {
	if x != nil {
		return x.ScreenshotUrl
	}
	return ""
}

type TestStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        TestStep_Status        `protobuf:"varint,2,opt,name=status,proto3,enum=siphon.TestStep_Status" json:"status,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStep) Reset() {
	*x = TestStep{}
	mi := &file_shared_proto_siphon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStep) ProtoMessage() {}

func (x *TestStep) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_siphon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStep.ProtoReflect.Descriptor instead.
func (*TestStep) Descriptor() ([]byte, []int) {
	return file_shared_proto_siphon_proto_rawDescGZIP(), []int{4}
}

func (x *TestStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestStep) GetStatus() TestStep_Status {
	if x != nil {
		return x.Status
	}
	return TestStep_UNKNOWN
}

func (x *TestStep) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_shared_proto_siphon_proto protoreflect.FileDescriptor

const file_shared_proto_siphon_proto_rawDesc = "" +
	"\n" +
	"\x19shared/proto/siphon.proto\x12\x06siphon\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\x17TestResultStreamRequest\x120\n" +
	"\n" +
	"test_suite\x18\x01 \x01(\v2\x11.siphon.TestSuiteR\ttestSuite\x12-\n" +
	"\ttest_case\x18\x02 \x01(\v2\x10.siphon.TestCaseR\btestCase\x12/\n" +
	"\n" +
	"test_steps\x18\x03 \x03(\v2\x10.siphon.TestStepR\ttestSteps\"N\n" +
	"\x18TestResultStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfa\x01\n" +
	"\tTestSuite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aproject\x18\x06 \x01(\tR\aproject\x12\x18\n" +
	"\arelease\x18\a \x01(\tR\arelease\x12\x16\n" +
	"\x06sprint\x18\b \x01(\tR\x06sprint\"\x9f\x02\n" +
	"\bTestCase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bsuite_id\x18\x02 \x01(\tR\asuiteId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.siphon.TestCase.StatusR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0escreenshot_url\x18\a \x01(\tR\rscreenshotUrl\"6\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04PASS\x10\x01\x12\b\n" +
	"\x04FAIL\x10\x02\x12\v\n" +
	"\aSKIPPED\x10\x03\"\xa8\x01\n" +
	"\bTestStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.siphon.TestStep.StatusR\x06status\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"6\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04PASS\x10\x01\x12\b\n" +
	"\x04FAIL\x10\x02\x12\v\n" +
	"\aSKIPPED\x10\x032j\n" +
	"\x0eIngressService\x12X\n" +
	"\x11StreamTestResults\x12\x1f.siphon.TestResultStreamRequest\x1a .siphon.TestResultStreamResponse(\x01B\x15Z\x13shared/proto/siphonb\x06proto3"

var (
	file_shared_proto_siphon_proto_rawDescOnce sync.Once
	file_shared_proto_siphon_proto_rawDescData []byte
)

func file_shared_proto_siphon_proto_rawDescGZIP() []byte {
	file_shared_proto_siphon_proto_rawDescOnce.Do(func() {
		file_shared_proto_siphon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_siphon_proto_rawDesc), len(file_shared_proto_siphon_proto_rawDesc)))
	})
	return file_shared_proto_siphon_proto_rawDescData
}

var file_shared_proto_siphon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shared_proto_siphon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shared_proto_siphon_proto_goTypes = []any{
	(TestCase_Status)(0),             // 0: siphon.TestCase.Status
	(TestStep_Status)(0),             // 1: siphon.TestStep.Status
	(*TestResultStreamRequest)(nil),  // 2: siphon.TestResultStreamRequest
	(*TestResultStreamResponse)(nil), // 3: siphon.TestResultStreamResponse
	(*TestSuite)(nil),                // 4: siphon.TestSuite
	(*TestCase)(nil),                 // 5: siphon.TestCase
	(*TestStep)(nil),                 // 6: siphon.TestStep
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_shared_proto_siphon_proto_depIdxs = []int32{
	4, // 0: siphon.TestResultStreamRequest.test_suite:type_name -> siphon.TestSuite
	5, // 1: siphon.TestResultStreamRequest.test_case:type_name -> siphon.TestCase
	6, // 2: siphon.TestResultStreamRequest.test_steps:type_name -> siphon.TestStep
	7, // 3: siphon.TestSuite.timestamp:type_name -> google.protobuf.Timestamp
	0, // 4: siphon.TestCase.status:type_name -> siphon.TestCase.Status
	1, // 5: siphon.TestStep.status:type_name -> siphon.TestStep.Status
	2, // 6: siphon.IngressService.StreamTestResults:input_type -> siphon.TestResultStreamRequest
	3, // 7: siphon.IngressService.StreamTestResults:output_type -> siphon.TestResultStreamResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_shared_proto_siphon_proto_init() }
func file_shared_proto_siphon_proto_init() {
	if File_shared_proto_siphon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_siphon_proto_rawDesc), len(file_shared_proto_siphon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_siphon_proto_goTypes,
		DependencyIndexes: file_shared_proto_siphon_proto_depIdxs,
		EnumInfos:         file_shared_proto_siphon_proto_enumTypes,
		MessageInfos:      file_shared_proto_siphon_proto_msgTypes,
	}.Build()
	File_shared_proto_siphon_proto = out.File
	file_shared_proto_siphon_proto_goTypes = nil
	file_shared_proto_siphon_proto_depIdxs = nil
}
